### ISSUE TITLE
Incompatible PIL version

### ISSUE THREAD

**Issue by olek-osikowicz** [IntelLabs/csg#11]
In the latest commit `c2bdd66` you bumped the PIL version to 10.0.1.

However, it breaks your code in the following way:
`Traceback (most recent call last):
  File "CSG.py", line 1859, in <module>
    tool = MainGUI(root)
  File "CSG.py", line 346, in __init__
    warning_thumb=ImageOps.fit(warning_icon, self.icon_image_size, Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
`
This is because `PIL.Image.ANTIALIAS` was deprecated in 10.0.0.
Source: https://stackoverflow.com/questions/76616042/attributeerror-module-pil-image-has-no-attribute-antialias

I'll submit PR with the fix.

**Comment by lidanzha** [comment]
Thanks for your help. Have merged.
